# Persistence layer: Mongo
db:
  image: pemarchandet/mongo-asv-la-soiree:v1.1.0
  extends:
    file: common.yml
    service: db
  restart: always
# Application server: NodeJS (Meteor)
server:
  image: pemarchandet/meteor-asv-la-soiree:v1.1.1
  extends:
    file: common.yml
    service: server
  links:
    - db
  environment:
    ROOT_URL: "https://www.asv-la-soiree.com"
  restart: always
# Front layer, static file, SSL, proxy cache: NGinx
front:
  image: pemarchandet/nginx-asv-la-soiree:v1.1.1
  extends:
    file: common.yml
    service: front
  links:
    - server
  environment:
    # Can be: dev, pre, prod
    HOST_TARGET: "prod"
  restart: always
