db:
  build: mongo
  volumes:
    - /var/db:/db
  expose:
    - "27017"
server:
  build: meteor
  links:
    - db
  environment:
    MONGO_URL: "mongodb://db:27017"
  ports:
    - "3000:3000"
  expose:
    - "3000"
  # environment:
  #   MONGO_URL: "mongodb://db:27017"
  #   MONGO_OPLOG_URL: "mongodb://db:27017/local"
  # environment:
  #   MONGO_URL: "mongodb://172.17.0.68:27017"
# front:
#   build: nginx
#   ports:
#     - "80:80"
#   links:
#     - server
