db:
  build: mongo
  volumes:
    - /var/db:/db
  expose:
    - "27017"
server:
  build: meteor
  links:
    - db
  environment:
    MONGO_URL: "mongodb://db:27017"
    MONGO_OPLOG_URL: "mongodb://db:27017/local"
    PORT: 3000
    ROOT_URL: "http://192.168.1.50"
  expose:
    - "3000"
front:
  build: nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - server
